# Copyright 2020 Huy Le Nguyen (@usimarit)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: null
  blank_at_zero: False
  beam_width: 500
  lm_config:
    model_path: null
    alpha: 2.0
    beta: 1.0

model_config:
  name: jasper
  dense: True
  first_additional_block_channels: 256
  first_additional_block_kernels: 11
  first_additional_block_strides: 2
  first_additional_block_dilation: 1
  first_additional_block_dropout: 0.2
  nsubblocks: 3
  block_channels: [256, 384, 512, 640, 768]
  block_kernels: [11, 13, 17, 21, 25]
  block_dropout: [0.2, 0.2, 0.2, 0.3, 0.3]
  second_additional_block_channels: 896
  second_additional_block_kernels: 1
  second_additional_block_strides: 1
  second_additional_block_dilation: 2
  second_additional_block_dropout: 0.4
  third_additional_block_channels: 1024
  third_additional_block_kernels: 1
  third_additional_block_strides: 1
  third_additional_block_dilation: 1
  third_additional_block_dropout: 0.4

learning_config:
  augmentations: null

  dataset_config:
    train_paths:
      - /mnt/d/Datasets/Speech/LibriSpeech/train-clean-100/transcripts.tsv
    eval_paths:
      - /mnt/d/Datasets/Speech/LibriSpeech/dev-clean/transcripts.tsv
      - /mnt/d/Datasets/Speech/LibriSpeech/dev-other/transcripts.tsv
    test_paths:
      - /mnt/d/Datasets/Speech/LibriSpeech/test-clean/transcripts.tsv
    tfrecords_dir: null

  optimizer_config:
    class_name: adam
    config:
      learning_rate: 0.0001

  running_config:
    batch_size: 4
    num_epochs: 20
    accumulation_steps: 8
    outdir: /mnt/d/Models/local/jasper
    log_interval_steps: 400
    save_interval_steps: 400
    eval_interval_steps: 800
